/* Generated by Together */

import java.util.*;

public class Evolver {
    public Generation gen0, gen1;
    private DataSet data;
    private int percentCrossover;

    Evolver(Generation gen, DataSet d, Random rand) {
        gen0 = gen;
        data = d;
    }

    public void makeNewGeneration(DataSet d, Random rand) {
        // gen1 is a copy of gen0; after this copy, gen0 is history, and
        // will be filled with new trees.
        gen1 = new Generation(gen0.getNumTrees());
        // copy gen0 into gen1
        for (int i = 0; i < gen0.getNumTrees(); i++) {
            gen1.replaceTree(i, gen0.getTree(i).duplicate());
        }
        // now gen0 is officially dead
        gen1.evalAll(d);
        // now gen0 rises from the ashes
        for (int i = 0; i < gen0.getNumTrees() / 2; i++) { // careful here?
            GPTree t1 = gen1.chooseTreeProportionalToFitness(rand);
            GPTree t2 = gen1.chooseTreeProportionalToFitness(rand);
            gen0.replaceTree(2 * i, t1.duplicate());
            gen0.replaceTree(2 * i + 1, t2.duplicate());
            gen0.crossover(gen0.getTree(2 * i), gen0.getTree(2 * i + 1), rand);
        }
        // So print the new gen0
        gen0.evalAll(d);
        System.out.println();
        //System.out.println("The new generation is:");
        // gen0.printGenFitness();
    }

    public void printGen0() {
        System.out.println();
        System.out.println("Here is Generation 0:");
        gen0.printGeneration();
    }

    public void printGen1() {
        System.out.println();
        System.out.println("Here is Generation 1:");
        gen1.printGeneration();
    }
}
