/* Generated by Together */
/*Modified to connect to the bridge class*/

import java.util.*;

public class TestEvolver {
    
	int maxDepth=3;
	String result ="";
		
		public void testEvolver(){}
		public TestEvolver(int generationNum, int treeNum, int randomSeed,
				Node[] userop, String filename) {  //A Constructor that require necessary parameters
	    Random rand = new Random(randomSeed);	
        DataSet ds = new DataSet(filename);
   		Node[] ops = userop.clone();
   	 	OperatorFactory o = new OperatorFactory(ops);
    	TerminalFactory t = new TerminalFactory(ds.numIndepVars());
        Generation g = null;
        g = new Generation(treeNum, o, t, maxDepth, rand);
        g.evalAll(ds);
        Evolver e = new Evolver(g, ds, rand);
        for (int i = 0; i < generationNum; i++) {
        	e.makeNewGeneration(ds, rand);
        	
        result += "The Best Tree in Generation " + i +" is " +(e.gen0.printBestTree());	
        }

		}
		public String getresult(){ //add a getmethod to retunr the results to the bridage class for further use,
			return result;  
		}
}
